### PR TITLE
fix: disable restrict saving in photoviewer

### PR DESCRIPTION
**Pull request by Henvy-Mango**
# Tittle Here

disable restrict saving in photoviewer
## Description

continue #88 
add `SaveToGallery` in photoviewer in `Restrict Saving Content` group or channel

IMG(1)

Screenshot nullgram(1)

## Check List

- [x] I have tested the changes and verified that they work and don't break anything(as well as I can manage) or drop the support for previous versions.
- [x] My code follows the code style of this project
- [x] I have merged commits that are meaningless for follow-up work and confirmed that they will not cause damage to follow-up maintenance

### CODE REVIEW

**Comment by Henvy-Mango** [comment]
在聊天界面可以正常保存，查看大图就保存不了
你看看这个思路行不行 @qwq233

**Comment by qwq233** [comment]
@Henvy-Mango Chat activity你看看改了没

**Comment by Henvy-Mango** [comment]
@qwq233 chat activity应该是正常的，不需要改

**Review by qwq233 — APPROVED** [review]

**Comment by qwq233** [comment]
感谢支持

**Pull request merged**
